version: '2.1'

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  backend:
    image: backend
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    depends_on:
      - mongo
